import 'package:url_launcher/url_launcher.dart';

/// Email service for sending notifications about at-risk students
class EmailService {
  // Sender email (for display purposes)
  static const String senderEmail = 'sudhan4843@gmail.com';

  // Student-specific email mapping
  static const Map<String, String> studentEmails = {
    'Joshua Walker': 'doodledevil2020@gmail.com',
    // Add more student mappings as needed
  };

  // Default counselor email
  static const String defaultRecipient = 'counselor@university.edu';

  /// Send an alert email about a student
  static Future<bool> sendStudentAlert({
    required String studentName,
    required String studentId,
    required int riskScore,
    required String riskLevel,
    List<String>? triggeredRules,
  }) async {
    // Get recipient based on student name
    final recipient = studentEmails[studentName] ?? defaultRecipient;

    // Build email subject
    final subject = Uri.encodeComponent(
      '[$riskLevel Risk] Student Alert: $studentName ($studentId)',
    );

    // Build email body
    final rulesText = triggeredRules != null && triggeredRules.isNotEmpty
        ? '\n\nTriggered Rules:\n${triggeredRules.map((r) => '• $r').join('\n')}'
        : '';

    final body = Uri.encodeComponent('''
Dear Counselor,

This is an automated alert from the Academic Stress Early Warning System.

Student Details:
- Name: $studentName
- ID: $studentId
- Current Risk Score: $riskScore/100
- Risk Level: $riskLevel$rulesText

Recommended Action:
Please review the student's profile and consider scheduling a check-in meeting.

This email was generated by the Stress Monitor App.

Best regards,
Academic Stress Early Warning System
''');

    // Create mailto URL
    final mailtoUrl = Uri.parse('mailto:$recipient?subject=$subject&body=$body');

    try {
      if (await canLaunchUrl(mailtoUrl)) {
        await launchUrl(mailtoUrl);
        return true;
      } else {
        return false;
      }
    } catch (e) {
      return false;
    }
  }

  /// Check if student has a configured email
  static bool hasStudentEmail(String studentName) {
    return studentEmails.containsKey(studentName);
  }

  /// Get student's configured email
  static String? getStudentEmail(String studentName) {
    return studentEmails[studentName];
  }
}
